spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: ge-takt-uaa
  flyway:
      schemas: public
      outOfOrder: true
      baselineOnMigrate: true
      table: schema_history_user_service
  jpa:
    open-in-view: false

server:
  port: ${vcap.application.port:8086} # Indicate the default PORT where this service will be started

logging:
  level:
    org:
      springframework:
        web: WARN
      hibernate : WARN
    com.sysmex.bcqmun: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3

config:
  oauth2:
    privateKey: '-----BEGIN RSA PRIVATE KEY----- MIIEowIBAAKCAQEAl3X+hG1gow4UBkJae//wE1hb80O+gaAJL/X8As7bCKUkFFER yu3rM27xdvOUlWmlfzQAEQIrMlJiN4R0W0lutaK/eojmGSF6FojewEgqEY6hCJO4 FVvI1KBTDmzTNY+Rc1hweAEdIhexUf4182B5G1zr26P57l86S1UOT/PWvVl5YqgC q6gxvLOd9k3g1O21ZDN/eRYfXLh5eochIqBJ70PFS98iNoOwlas7mwcxVnHoMDGz JJIocga85ZoPk2nYdRd6L7zCZwy25VSJgDiaYuoB9o2KVfloTboYPeT5TkQGqFLU eeoBCkIGSP7rsa6xF2o1HpPp+y4RHb4HdxwZdQIDAQABAoIBAGYp0wokdSDHKD6o lzw5AQkreqp2MZRiDJBrThfey+Pi8Jk7rdLB9Pp2hS2FU94MqvNIchsG6XhCFbn5 ADtrJuAh7SKMIRkmeaGlpQryIl5BZOHSMkNF7AtwMVXzlev08VlqeEKaDbqnXJY/ 8Mg/dLE+VmGLE9T0KvARaVwIz/pbzE/zc10YlbryQerI4smIfHTDi4gjZkN2/CBM 1H6UvmzPX1csEdCFTYVIjQpjkIAHnHtg+JgYxlV6bzPi0CKSyEBSDeeV0xJVbIpf YJ3GVatqfUSHhWQ6GIyxUitnw+5rVXPl3RdYECgBxTZx/xlqbFJa2G4L5xcJ9trd h3/ROikCgYEAyPAVHT48Xhymieedt76xnS9maN711ENW3363a9atoyDx/E8KYQa6 dm4ad+K89B3IYSeFOX2Qhj2rC+9c0CdeqcZaC/oxirQVDhlrAThZd6kPQRBii4c/ gEuiSo541DRDYG4f27N/TOxFuAaS3pH5F3GOknA7XUZP3IvOoNX95xcCgYEAwPcT KSgXP8U054Gl1OrCdYE1X0UtZuoYgk1j8YEIgFIx4xQ6/AU//XviDsRGJT+oPShC 6m7cHdemeSJVFWrMkIWoBoE5G6Vvxcykc2Q4HOPZtQh4PLE9tN5T/ad9MprzY3X0 j73CHetoI9I99/SCwZEnZroKu/e/rOpN/XejW1MCgYB4a8l7mQy8qhb0lqZitBnl xb5uIxDYgPLTRjHOov20wc3EE+p4c3vT9fBO4Me01RR9hR3GcoXmrZaQtIa/CJkm zgSxIOQH6BymMn16Ybbci6jkqVklnYxk6u78F546Logihlz5Yf1ssDyoKOhkEr9h WWDEShaJs9WwqujOYvCjSQKBgQDAcOfkAL6G85aaVvraR7HdXBmtRKFN5KLCuIm2 3VdsGgz0iUV194pkszq0PVwzY7PWIiPyBtNw05OLdQjjjhoq+5ChxBf/EVNSMY/E IKuxbC6/U44OATkn+x5KdtHuOQgIJifbfoRsMEwwhUkV0vzgLHHeCiYQZbj7qsRS xxDcTwKBgA23K3PndUF0LrFcNE3ERB7LU8Ta4DA8GCxMsvNYIvnlYNmwyALeuwI1 Cj+MqcM0kCjlqzQXHJor6wEi0qpXJaiA/+RL4bSjAixWi5tMpZL9Efu0Kvr+hsmE p1H8N53aDbcO866VMaUNIV/ZarT/TtgwJVzp3ZFkOIrNhFXne6y3 -----END RSA PRIVATE KEY-----'
    publicKey: '-----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl3X+hG1gow4UBkJae//w E1hb80O+gaAJL/X8As7bCKUkFFERyu3rM27xdvOUlWmlfzQAEQIrMlJiN4R0W0lu taK/eojmGSF6FojewEgqEY6hCJO4FVvI1KBTDmzTNY+Rc1hweAEdIhexUf4182B5 G1zr26P57l86S1UOT/PWvVl5YqgCq6gxvLOd9k3g1O21ZDN/eRYfXLh5eochIqBJ 70PFS98iNoOwlas7mwcxVnHoMDGzJJIocga85ZoPk2nYdRd6L7zCZwy25VSJgDia YuoB9o2KVfloTboYPeT5TkQGqFLUeeoBCkIGSP7rsa6xF2o1HpPp+y4RHb4HdxwZ dQIDAQAB -----END PUBLIC KEY-----'
    tokenTimeout: 360000000
    resource:
      id: oauth2-resource-swagger-ui
    clientID: 'my-client-id'
    clientSecret: 'my-secret-key'
    accessTokenUri: ${vcap.services.ge-takt-system-info.credentials.uaa.uri:http://taktdemo.xyz:8086}/oauth/token