spring:
  datasource:
    url: jdbc:postgresql://${vcap.services.predix_postgres_ge_takt_dev.credentials.hostname}:5432/postgres
    username: ${vcap.services.ge-takt-postgres.credentials.username}
    password: ${vcap.services.ge-takt-postgres.credentials.password}

eureka:
  instance:
    hostname: ${vcap.application.application_uris[0]}
    instance-id: ${spring.application.name}:${random.int}
    secure-port: 443
    non-secure-port: 443
    secure-port-enabled: true
    non-secure-port-enabled: false
    prefer-ip-address: false
    home-page-url: https://${eureka.instance.hostname}:${eureka.instance.secure-port}
    secure-virtual-host-name: https://${vcap.application.application_uris[0]}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.ge-takt-system-info.credentials.registry.uri}/eureka